linters:
  enable:
    - misspell
    - unconvert
    - whitespace
    - nilerr
    - bodyclose

linters-settings:
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 5m
